name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Sources configuration
sources:
  - name: dbt_schema
    database: dbt_db  # Your Snowflake database
    schema: dbt_schema  # Your Snowflake schema
    tables:
      - name: staging_data  # The name of the table in your database

# Configuring models
models:
  my_new_project:
    example:
      +materialized: table
